require("user.options")
require("user.keymaps")
require("user.packer")
require("user.nvimtree")
require("user.treesitter")
require("user.nvim-cmp")
require("lsp.lsp-config")
require("lsp.mason")
require("user.autopairs")
require("user.comment")
require("user.telescope")
vim.api.nvim_command "colorscheme catppuccin-macchiato"
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
