require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.nvimtree")
require("user.treesitter")
require("user.nvim-cmp")
require("lsp.lsp-config")
require("lsp.mason")
require("user.autopairs")
require("user.comment")
require("user.telescope")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
require("lsp.null-ls")
require("user.gitsigns")

