theme = "catppuccin_macchiato"
[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "always"
idle-timeout=0
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["version-control","mode", "diagnostics", "file-name"]
right = ["file-type","file-encoding","position"]

[editor.soft-wrap]
enable = true
wrap-indicator = ""
max-wrap = 25

[keys.insert.j]
k = "normal_mode"

[keys.normal]
C-p = "file_picker"
L = "goto_next_buffer"
H= "goto_previous_buffer"
[keys.normal.space]
d = ":buffer-close"
D = ":buffer-close!"
t = "diagnostics_picker"
T = "workspace_diagnostics_picker"


